### ISSUE TITLE
ERROR!

### ISSUE THREAD

**Issue by nejmik242** [Iridium-Development/IridiumSkyblock#115]
[10:09:56 INFO]: Nejmik242 issued server command: /is reload
[10:09:56 ERROR]: [IridiumSkyblock] Failed to parse plugins\IridiumSkyblock\upgrades.yml: Cannot construct instance of `com.iridium.iridiumcore.utils.Placeholder` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (File); line: 31, column: 9] (through reference chain: com.iridium.iridiumskyblock.configs.Upgrades["sizeUpgrade"]->com.iridium.iridiumskyblock.Upgrade["upgrades"]->java.util.LinkedHashMap["1"]->com.iridium.iridiumskyblock.upgrades.SizeUpgrade["placeholders"]->java.util.Collections$SingletonList[1])
[10:09:56 INFO]: [IridiumSkyblock] Disabling IridiumSkyblock v3.0.1
[10:09:56 INFO]: [IridiumSkyblock] -------------------------------
[10:09:56 INFO]: [IridiumSkyblock]
[10:09:56 INFO]: [IridiumSkyblock] IridiumSkyblock Disabled!
[10:09:56 INFO]: [IridiumSkyblock]
[10:09:56 INFO]: [IridiumSkyblock] -------------------------------
[10:09:56 ERROR]: [IridiumSkyblock] Failed to parse plugins\IridiumSkyblock\shop.yml: Unrecognized field "purchasable" (class com.iridium.iridiumskyblock.shop.ShopItem), not marked as ignorable (8 known properties: "sellReward", "buyCost", "lore", "defaultAmount", "type", "name", "slot", "command"])
 at [Source: (File); line: 77, column: 22] (through reference chain: com.iridium.iridiumskyblock.configs.Shop["items"]->java.util.LinkedHashMap["Blocks"]->java.util.ArrayList[0]->com.iridium.iridiumskyblock.shop.ShopItem["purchasable"])
[10:09:59 INFO]: Nejmik242 issued server command: /is
[10:09:59 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'is' in plugin IridiumSkyblock v3.0.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.5.jar:git-Purpur-1111]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-1111]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2306) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2121) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2074) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1336) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1329) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1305) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1149) ~[patched_1.16.5.jar:git-Purpur-1111]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1111]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]

Server version: This server is running Purpur version git-Purpur-1111 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
Version plugin: 3.0.1

**Comment by dlsf** [comment]
Duplicate of #112
