### ISSUE TITLE
Problem with /is regen

### ISSUE THREAD

**Issue by FoxyFoxy67** [Iridium-Development/IridiumSkyblock#131]
Steps to reproduce : type /is regen

Click on Icons ( The Menu is not closed) 

[00:53:39] [Server thread/ERROR]: Could not pass event InventoryClickEvent to IridiumSkyblock v3.0.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2435) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(SourceFile:103) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1037) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.iridium.iridiumskyblock.managers.IslandManager.deleteIslandBlocks(IslandManager.java:266) ~[?:?]
        at com.iridium.iridiumskyblock.managers.IslandManager.regenerateIsland(IslandManager.java:210) ~[?:?]
        at com.iridium.iridiumskyblock.gui.IslandRegenGUI.selectSchematic(IslandRegenGUI.java:41) ~[?:?]
        at com.iridium.iridiumskyblock.gui.SchematicGUI.onInventoryClick(SchematicGUI.java:60) ~[?:?]
        at com.iridium.iridiumskyblock.listeners.InventoryClickListener.onInventoryClick(InventoryClickListener.java:14) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor160.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:3068-Spigot-bd6b566-59e2ce9]
        ... 18 more

**Comment by shawn3308** [comment]
which server version 
and java version

**Comment by FoxyFoxy67** [comment]
Version : 1.16.5
Iridium Version : 3.0.3
Server Api : Spigot 1.16.5

Minecraft Hosted on Linux Ubuntu 20.04

**Comment by FoxyFoxy67** [comment]
Need others Informations ?

**Comment by shawn3308** [comment]
delete the worlds and plugin folder

**Comment by shawn3308** [comment]
whats the java version

**Comment by dlsf** [comment]
> delete the worlds and plugin folder

I don't exactly know what your mission here is, but please don't recommend random stuff. Java version is also completely irrelevant.

@FoxyFoxy67 please visit our support Discord and try the beta jar in the #sharing channel. If the error still occurs, send us the updated error message, please.

**Comment by shawn3308** [comment]
use java 10 thats all

**Comment by PeachesMLG** [comment]
> > delete the worlds and plugin folder
> 
> I don't exactly know what your mission here is, but please don't recommend random stuff. Java version is also completely irrelevant.
> 
> @FoxyFoxy67 please visit our support Discord and try the beta jar in the #sharing channel. If the error still occurs, send us the updated error message, please.

This, and ive pinned the latest jar for you :)

**Comment by FoxyFoxy67** [comment]
Okay , Thanks i come on discord

**Comment by FoxyFoxy67** [comment]
Problem Solved ! Thanks
