### ISSUE TITLE
ConcurrentModificationException when saving to the database

### ISSUE THREAD

**Issue by antasetyawan** [Iridium-Development/IridiumSkyblock#155]
[18:48:41 WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v3.0.4 generated an exception while executing task 571
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at com.iridium.iridiumskyblock.managers.tablemanagers.TableManager.save(TableManager.java:42) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.saveData(IridiumSkyblock.java:284) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-775]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-775]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-775]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Nubebuster** [comment]
I had this too today

**Comment by PeachesMLG** [comment]
Should be fixed now
