### ISSUE TITLE
is rewards doesnt work

### ISSUE THREAD

**Issue by notmoving3** [Iridium-Development/IridiumSkyblock#170]
https://pastebin.pl/view/995bbb41

last version of skyblock, and 1.16.5

**Comment by dlsf** [comment]
That's not the whole error message, can you please send all of it?

**Comment by notmoving3** [comment]
[12:55:20] [Server thread/ERROR]: Could not pass event InventoryClickEvent to IridiumSkyblock v3.0.4
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin IridiumSkyblock v3.0.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at com.iridium.iridiumskyblock.gui.InventoryConfigGUI.onInventoryClick(InventoryConfigGUI.java:43) ~[?:?]
	at com.iridium.iridiumskyblock.listeners.InventoryClickListener.onInventoryClick(InventoryClickListener.java:14) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor225.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2797) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1325) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException

**Comment by dlsf** [comment]
There is still the most important part missing at the bottom of these lines

**Comment by dlsf** [comment]
> No is not XDDDDD

Are you using some tool (webinterface, ...) that might shorten it? Please try to find it in the latest.log

**Comment by notmoving3** [comment]
OFCOURSE ITS LASTEST.LOG i dont use anything the full error you can clearly see there
[12:55:20] [Server thread/ERROR]: Could not pass event InventoryClickEvent to IridiumSkyblock v3.0.4
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin IridiumSkyblock v3.0.4
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at com.iridium.iridiumskyblock.gui.InventoryConfigGUI.onInventoryClick(InventoryConfigGUI.java:43) ~[?:?]
at com.iridium.iridiumskyblock.listeners.InventoryClickListener.onInventoryClick(InventoryClickListener.java:14) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor225.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2797) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1325) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1318) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NullPointerException

**Comment by dlsf** [comment]
Well, something is wrong with your error message, maybe it's airplanes fault. We recommend Paper as the server software, it's a fork of Airplane. Additionally, installing Java 16 as it's recommended by Minecraft, Paper and us would also help a lot.

Assuming that that's really the whole error message, this is not the fault of IridiumSkyblock but your server software. I don't want to argue with you, but I've never seen such an error message in my 5 years of Java programming.

**Comment by dlsf** [comment]
Please comment on this issue if you can provide more information (for instance by switching your server software or using another Java version)

**Comment by Nubebuster** [comment]
The stacktrace is simply ordered in reverse.

Could you paste your inventories.yml on hastebin?

**Comment by dlsf** [comment]
> The stacktrace is simply ordered in reverse.

But there is a block under the "Caused by:" line in normal error messages

**Comment by PeachesMLG** [comment]
I believe in order to stop spam, if an error message is repeated alot within a certain time it shortens it

**Comment by dlsf** [comment]
But you don't shorten it so that the most important part is left out

**Comment by PeachesMLG** [comment]
PM me on discord and send me the log file in your logs folder that contains this message

**Comment by MertUnverdi** [comment]
Still exist?

**Comment by MertUnverdi** [comment]
No response
