### ISSUE TITLE
A lot of this error spam, BlockBreakEvent las version of skyblock 1.16.5

### ISSUE THREAD

**Issue by notmoving3** [Iridium-Development/IridiumSkyblock#172]
[19:52:08 ERROR]: Could not pass event BlockBreakEvent to IridiumSkyblock v3.0.4
java.lang.NullPointerException: null
[19:52:08 WARN]: [IridiumSkyblock] Task #57 for IridiumSkyblock v3.0.4 generated an exception
java.lang.NullPointerException: null
[19:52:08 ERROR]: Could not pass event BlockBreakEvent to IridiumSkyblock v3.0.4
java.lang.NullPointerException: null
[19:52:09 ERROR]: Could not pass event BlockBreakEvent to IridiumSkyblock v3.0.4
java.lang.NullPointerException: null
[19:52:09 ERROR]: Could not pass event BlockPlaceEvent to IridiumSkyblock v3.0.4
java.lang.NullPointerException: null
[19:52:09 ERROR]: Could not pass event BlockBreakEvent to IridiumSkyblock v3.0.4
java.lang.NullPointerException: null
[19:52:09 ERROR]: Could not pass event BlockBreakEvent to IridiumSkyblock v3.0.4
java.lang.NullPointerException: null
[19:52:10 ERROR]: Could not pass event BlockBreakEvent to IridiumSkyblock v3.0.4
java.lang.NullPointerException: null
[19:52:10 ERROR]: Could not pass event BlockBreakEvent to IridiumSkyblock v3.0.4
java.lang.NullPointerException: null
[19:52:10 ERROR]: Could not pass event BlockBreakEvent to IridiumSkyblock v3.0.4
java.lang.NullPointerException: null
[19:52:10 ERROR]: Could not pass event Blo

**Comment by dlsf** [comment]
That's not a Java error message, it's shortened. Could you please provide the full error message (for instance from the latest.log)?

**Comment by notmoving3** [comment]
[12:03:28] [Server thread/WARN]: [IridiumSkyblock] Task #57 for IridiumSkyblock v3.0.4 generated an exception
java.lang.NullPointerException: null
	at com.iridium.iridiumskyblock.managers.tablemanagers.ForeignIslandTableManager.getIndex(ForeignIslandTableManager.java:90) ~[?:?]
	at com.iridium.iridiumskyblock.managers.tablemanagers.ForeignIslandTableManager.getEntries(ForeignIslandTableManager.java:46) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandManager.recalculateIsland(IslandManager.java:627) ~[?:?]
	at com.iridium.iridiumskyblock.IridiumSkyblock$1.lambda$run$0(IridiumSkyblock.java:177) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_292]
	at com.iridium.iridiumskyblock.IridiumSkyblock$1.run(IridiumSkyblock.java:177) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1489) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1402) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-"a13c511"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by PeachesMLG** [comment]
Message me on discord, and Ill give you a newer jar for you to try
