### ISSUE TITLE
Issue on startup on specific server version

### ISSUE THREAD

**Issue by TheJoshue** [Iridium-Development/IridiumSkyblock#189]
Using paper-1.12.2 (1618) server version.
Running on Windows 10 & Ubuntu18.04, running Java 8
I get this error on startup (running latest spigotmc release = v3.0.4)
```[01:44:23 INFO]: [IridiumSkyblock] Successfully registered placeholders with PlaceholderAPI.
[01:44:24 ERROR]: Error occurred while enabling IridiumSkyblock v3.0.4 (Is it up to date?)
java.lang.NoSuchMethodError: de.jeff_media.updatechecker.UpdateChecker.checkNow()Lde/jeff_media/updatechecker/UpdateChecker;
        at com.iridium.iridiumskyblock.IridiumSkyblock.onEnable(IridiumSkyblock.java:196) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[Paper-1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[Paper-1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[Paper-1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[01:44:24 INFO]: [IridiumSkyblock] Disabling IridiumSkyblock v3.0.4
[01:44:24 INFO]: [IridiumSkyblock] -------------------------------
[01:44:24 INFO]: [IridiumSkyblock]
[01:44:24 INFO]: [IridiumSkyblock] IridiumSkyblock Disabled!
[01:44:24 INFO]: [IridiumSkyblock]
[01:44:24 INFO]: [IridiumSkyblock] -------------------------------
```

By so, plugin is basically disabled and not working.

I tried running on 1.16.5 paper, it works flawlessly, however I didn't test other older MC versions, just 1.12.2.

**Comment by dlsf** [comment]
Fixed by #151, please join our Discord and ask for a beta jar or download one from Github Actions (master branch!) yourself
