### ISSUE TITLE
Not able to claim rewards

### ISSUE THREAD

**Issue by draand28** [Iridium-Development/IridiumSkyblock#216]
I'm using Paper 1.8.8 build 443 and IridiumSkyblock 3.0.5. I was testing the plugin and I leveled up and receive some money and crystals, but the */is redeem* menu is full of gray glass and the console outputs the following error:
`[23:09:53 WARN]: [IridiumSkyblock] Task #2273 for IridiumSkyblock v3.0.5 generated an exception
java.lang.NullPointerException
        at com.iridium.iridiumskyblock.managers.tablemanagers.ForeignIslandTableManager.getEntries(ForeignIslandTableManager.java:69) ~[?:?]
        at com.iridium.iridiumskyblock.database.Island.getValue(Island.java:204) ~[?:?]
        at com.iridium.iridiumskyblock.PlaceholderBuilder.applyIslandPlaceholders(PlaceholderBuilder.java:24) ~[?:?]
        at com.iridium.iridiumskyblock.gui.RewardsGUI.addContent(RewardsGUI.java:32) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$null$3(IridiumSkyblock.java:193) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_292]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082) ~[?:1.8.0_292]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$4(IridiumSkyblock.java:190) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
[23:09:54 WARN]: [IridiumSkyblock] Task #2273 for IridiumSkyblock v3.0.5 generated an exception
java.lang.NullPointerException
`

**Comment by draand28** [comment]
The issues seems fixed in 3.0.6.
