### ISSUE TITLE
IridiumSkyblock fatal error in server start

### ISSUE THREAD

**Issue by Akomry38** [Iridium-Development/IridiumSkyblock#241]
The plugin is disabled in the server start. Here are the errors.
Server version : paper 1.16.5-779
Plugin version : Iridium Skyblock 3.0.6 (still errors in 3.0.5)
Errors : https://pastebin.com/CHNv49N8

**Comment by Akomry38** [comment]
i tried changing my java version to 15 hotspot with spigot and now it shows in green in /plugins but when i try any command it does nothing, in game and in the console
i still have this error
```
[21:48:13] [Server thread/INFO]: [IridiumSkyblock] Enabling IridiumSkyblock v3.0.5
[21:48:13] [Server thread/ERROR]: Error occurred while enabling IridiumSkyblock v3.0.5 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/class_2596
        at com.iridium.iridiumcore.MinecraftVersion.lambda$static$13(MinecraftVersion.java:30) ~[?:?]
        at com.iridium.iridiumcore.MinecraftVersion.getNms(MinecraftVersion.java:42) ~[?:?]
        at com.iridium.iridiumcore.IridiumCore.setupMultiVersion(IridiumCore.java:105) ~[?:?]
        at com.iridium.iridiumcore.IridiumCore.onEnable(IridiumCore.java:43) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.onEnable(IridiumSkyblock.java:117) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2596
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 15 more
```

**Comment by MertUnverdi** [comment]
is still exist at 3.0.7?

**Comment by MertUnverdi** [comment]
no response ??
it will be closed after 1 days (if i get forgot it, faun will do)
