### ISSUE TITLE
NullPointerException: Unsupported biome

### ISSUE THREAD

**Issue by xotrikspl** [Iridium-Development/IridiumSkyblock#256]
[15:07:02 WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Unsupported biome: LUSH_CAVES
[15:07:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[15:07:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[15:07:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[15:07:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[15:07:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705)
[15:07:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
[15:07:02 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[15:07:02 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[15:07:02 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[15:07:02 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[15:07:02 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[15:07:02 WARN]: Caused by: java.lang.NullPointerException: Unsupported biome: LUSH_CAVES
[15:07:02 WARN]:        at java.base/java.util.Objects.requireNonNull(Objects.java:347)
[15:07:02 WARN]:        at com.iridium.iridiumcore.dependencies.xseries.XBiome.setBiome(XBiome.java:298)
[15:07:02 WARN]:        at com.iridium.iridiumskyblock.managers.IslandManager.lambda$setIslandBiome$1(IslandManager.java:87)
[15:07:02 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
[15:07:02 WARN]:        ... 8 more

**Comment by dlsf** [comment]
What is the context? What did you change in the configs? When does this error occur? What version of IridiumSkyblock are you using?

**Comment by xotrikspl** [comment]
What version of IridiumSkyblock are you using? version 3.0.6 
What did you change in the configs? - NO
When does this error occur? - i don't know ;(

**Comment by dlsf** [comment]
Sorry, I forgot to ask what Minecraft version are you using?

**Comment by xotrikspl** [comment]
Version 1.16.5

**Comment by dlsf** [comment]
Alright, I suppose I know the issue then
