### ISSUE TITLE
BlockFormEvent null pointer error

### ISSUE THREAD

**Issue by xReveres** [Iridium-Development/IridiumSkyblock#275]
After 10min. server spam this error:
> [18:55:53] [Server thread/ERROR]: Could not pass event BlockFormEvent to IridiumSkyblock v3.0.6
java.lang.NullPointerException: null
	at com.iridium.iridiumskyblock.listeners.BlockFormListener.onBlockForm(BlockFormListener.java:46) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor330.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-715]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-715]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-715]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-715]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1717) ~[patched_1.16.5.jar:git-Paper-715]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1709) ~[patched_1.16.5.jar:git-Paper-715]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleBlockFormEvent(CraftEventFactory.java:1668) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.BlockFluids.a(BlockFluids.java:159) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.BlockFluids.onPlace(BlockFluids.java:103) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.BlockBase$BlockData.onPlace(BlockBase.java:610) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.Chunk.setType(Chunk.java:571) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.World.a(World.java:465) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.World.setTypeAndData(World.java:427) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.FluidTypeFlowing.a(FluidTypeFlowing.java:301) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.FluidTypeLava.a(FluidTypeLava.java:190) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.FluidTypeFlowing.a(FluidTypeFlowing.java:192) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.FluidTypeFlowing.a(FluidTypeFlowing.java:157) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.FluidTypeFlowing.a(FluidTypeFlowing.java:505) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.Fluid.a(Fluid.java:56) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.WorldServer.a(WorldServer.java:913) ~[patched_1.16.5.jar:git-Paper-715]
	at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:306) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.TickListServer.b(TickListServer.java:59) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:582) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1489) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1341) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1129) ~[patched_1.16.5.jar:git-Paper-715]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-715]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by dlsf** [comment]
Fixed by #269
