### ISSUE TITLE
Unsupported mods (Forge)

### ISSUE THREAD

**Issue by Serega007RU** [Iridium-Development/IridiumSkyblock#278]
On Mohist (forge + bukkit) 1.12.2, when interacting with blocks from mods (not from vanilla minecraft) in the console, it spams these errors. There was no such problem on version 2.4.6 and everything worked fine

Here is one of these errors:
```
[11:53:38 ERROR]: Could not pass event PlayerInteractEvent to IridiumSkyblock v3.0.6
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:73) ~[TimedEventExecutor.class:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:331) ~[CraftEventFactory.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:501) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1148) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:61) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:13) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_231]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_231]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:846) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.lang.IllegalArgumentException: Unsupported material with no data value: TCONSTRUCT_TOOLTABLES
        at com.iridium.iridiumcore.dependencies.xseries.XMaterial.lambda$matchXMaterial$0(XMaterial.java:1690) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_231]
        at com.iridium.iridiumcore.dependencies.xseries.XMaterial.matchXMaterial(XMaterial.java:1690) ~[?:?]
        at com.iridium.iridiumskyblock.listeners.PlayerInteractListener.onPlayerInteract(PlayerInteractListener.java:44) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor22.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:?]
        ... 17 more\
````

**Comment by MertUnverdi** [comment]
i don't think we're supporting forge @dlsf ?

**Comment by dlsf** [comment]
That's correct, we don't

**Comment by Serega007RU** [comment]
OK, what is the latest version that supports Forge?

**Comment by dlsf** [comment]
It's so old that you won't want to use it. We don't support forge because the tool that we use for multiversion support does not.

We can ask them if they'll add support but I highly doubt it. That's pretty much the reason this issue is still open.

**Comment by Serega007RU** [comment]
I have no other choice, I know for sure that version 2.4.6 supports Forge, I'm just asking if there is a slightly newer version in which Forge is still supported

**Comment by PeachesMLG** [comment]
> It's so old that you won't want to use it. We don't support forge because the tool that we use for multiversion support does not.
> 
> We can ask them if they'll add support but I highly doubt it. That's pretty much the reason this issue is still open.

I mean I dont see how its possible for them to support forge, unless they manually add support for each mod which they 100% wont

**Comment by dlsf** [comment]
That server software he's using injects new constants into the Material enum so it's definitely possible
