### ISSUE TITLE
Island border bug

### ISSUE THREAD

**Issue by Farmeurimmo** [Iridium-Development/IridiumSkyblock#334]
When I'm starting my server I'm getting this error

`[12:18:39 WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot read field "size" because the return value of "java.util.Map.get(Object)" is null
[12:18:39 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[12:18:39 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[12:18:39 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766)
[12:18:39 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[12:18:39 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[12:18:39 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[12:18:39 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[12:18:39 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[12:18:39 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[12:18:39 WARN]: Caused by: java.lang.NullPointerException: Cannot read field "size" because the return value of "java.util.Map.get(Object)" is null
[12:18:39 WARN]:        at com.iridium.iridiumskyblock.database.Island.getSize(Island.java:249)
[12:18:39 WARN]:        at com.iridium.iridiumskyblock.database.Island.getPos1(Island.java:323)
[12:18:39 WARN]:        at com.iridium.iridiumskyblock.managers.IslandManager.lambda$getIslandChunks$17(IslandManager.java:352)
[12:18:39 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[12:18:39 WARN]:        ... 6 more`

and when I'm joining my island I'm getting this error

`[12:23:04] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to IridiumSkyblock v3.0.7
java.lang.NullPointerException: Cannot read field "size" because the return value of "java.util.Map.get(Object)" is null
	at com.iridium.iridiumskyblock.database.Island.getSize(Island.java:249) ~[?:?]
	at com.iridium.iridiumskyblock.database.Island.getPos1(Island.java:323) ~[?:?]
	at com.iridium.iridiumskyblock.database.Island.isInIsland(Island.java:372) ~[?:?]
	at com.iridium.iridiumskyblock.database.Island.isInIsland(Island.java:358) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandManager.lambda$getIslandViaLocation$21(IslandManager.java:448) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandManager.getIslandViaLocation(IslandManager.java:448) ~[?:?]
	at com.iridium.iridiumskyblock.listeners.PlayerTeleportListener.onPlayerTeleport(PlayerTeleportListener.java:18) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor77.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-779]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-779]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-779]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-779]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.teleport(CraftPlayer.java:898) ~[patched_1.16.5.jar:git-Paper-779]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.teleport(CraftEntity.java:539) ~[patched_1.16.5.jar:git-Paper-779]
	at com.iridium.iridiumskyblock.managers.IslandManager.teleportHome(IslandManager.java:158) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandManager.teleportHome(IslandManager.java:137) ~[?:?]
	at com.iridium.iridiumskyblock.commands.HomeCommand.execute(HomeCommand.java:43) ~[?:?]
	at com.iridium.iridiumskyblock.commands.CommandManager.onCommand(CommandManager.java:197) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-779]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-779]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1395) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-779]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

and when I'm moving on my island I'm getting this error

`[12:23:10] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to IridiumSkyblock v3.0.7
java.lang.NullPointerException: Cannot read field "size" because the return value of "java.util.Map.get(Object)" is null
	at com.iridium.iridiumskyblock.database.Island.getSize(Island.java:249) ~[?:?]
	at com.iridium.iridiumskyblock.database.Island.getPos1(Island.java:323) ~[?:?]
	at com.iridium.iridiumskyblock.database.Island.isInIsland(Island.java:372) ~[?:?]
	at com.iridium.iridiumskyblock.database.Island.isInIsland(Island.java:358) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandManager.lambda$getIslandViaLocation$21(IslandManager.java:448) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandManager.getIslandViaLocation(IslandManager.java:448) ~[?:?]
	at com.iridium.iridiumskyblock.managers.IslandManager.getIslandViaPlayerLocation(IslandManager.java:434) ~[?:?]
	at com.iridium.iridiumskyblock.listeners.PlayerMoveListener.onPlayerMove(PlayerMoveListener.java:33) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor102.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-779]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-779]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-779]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1424) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1220) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Paper-779]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-779]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by MertUnverdi** [comment]
please send ur database, it seems its has corrupted

**Comment by MertUnverdi** [comment]
it seems about ur upgrades.yml probably u changed something after island has upgraded

**Comment by MertUnverdi** [comment]
can u send it ?

**Comment by Farmeurimmo** [comment]
`---
sizeUpgrade:
  enabled: true
  item:
    material: "GRASS_BLOCK"
    amount: 1
    displayName: "&b&lIsland Size"
    headData: null
    headOwner: null
    lore:
    - "&7Need more room to expand? Buy this"
    - "&7upgrade to increase your island size."
    - ""
    - "&b&lInformation:"
    - "&b&l * &7Current Level: &b%level%"
    - "&b&l * &7Current Size: &b%size%x%size% Blocks"
    - "&b&l * &7Upgrade Cost: &b%crystalscost% Crystals and $%vaultcost%"
    - "&b&lLevels:"
    - "&b&l * &7Level 1: &b50x50 Blocks"
    - "&b&l * &7Level 2: &b100x100 Blocks"
    - "&b&l * &7Level 3: &b150x150 Blocks"
    - ""
    - "&b&l[!] &bLeft Click to Purchase this Upgrade"
    slot: 11
  upgrades:
    1:
      money: 1000
      crystals: 15
      size: 50
    2:
      money: 1000
      crystals: 15
      size: 100
    3:
      money: 1000
      crystals: 15
      size: 150
memberUpgrade:
  enabled: true
  item:
    material: "ARMOR_STAND"
    amount: 1
    displayName: "&b&lIsland Members"
    headData: null
    headOwner: null
    lore:
    - "&7Need more members? Buy this"
    - "&7upgrade to increase your member count."
    - ""
    - "&b&lInformation:"
    - "&b&l * &7Current Level: &b%level%"
    - "&b&l * &7Current Member: &b%amount% Members"
    - "&b&l * &7Upgrade Cost: &b%crystalscost% Crystals and $%vaultcost%"
    - "&b&lLevels:"
    - "&b&l * &7Level 1: &b9 Members"
    - "&b&l * &7Level 2: &b18 Members"
    - "&b&l * &7Level 3: &b27 Members"
    - ""
    - "&b&l[!] &bLeft Click to Purchase this Upgrade"
    slot: 12
  upgrades:
    1:
      money: 1000
      crystals: 15
      amount: 9
    2:
      money: 1000
      crystals: 15
      amount: 18
    3:
      money: 1000
      crystals: 15
      amount: 27
blockLimitUpgrade:
  enabled: true
  item:
    material: "HOPPER"
    amount: 1
    displayName: "&b&lIsland Block Limits"
    headData: null
    headOwner: null
    lore:
    - "&7Need to place more blocks? Buy this"
    - "&7upgrade to increase the amount of blocks you can place."
    - ""
    - "&b&lInformation:"
    - "&b&l * &7Current Level: &b%level%"
    - "&b&l * &7Upgrade Cost: &b%crystalscost% Crystals and $%vaultcost%"
    - ""
    - "&b&l[!] &bLeft Click to Purchase this Upgrade"
    slot: 13
  upgrades:
    1:
      money: 1000
      crystals: 15
      limits:
        HOPPER: 15
        PISTON: 10
        SPAWNER: 10
    2:
      money: 1000
      crystals: 15
      limits:
        HOPPER: 20
        PISTON: 15
        SPAWNER: 15
    3:
      money: 1000
      crystals: 15
      limits:
        HOPPER: 25
        PISTON: 20
        SPAWNER: 20
    4:
      money: 1000
      crystals: 15
      limits:
        HOPPER: 30
        PISTON: 25
        SPAWNER: 25
    5:
      money: 1000
      crystals: 15
      limits:
        HOPPER: 40
        PISTON: 30
        SPAWNER: 30
warpsUpgrade:
  enabled: true
  item:
    material: "END_PORTAL_FRAME"
    amount: 1
    displayName: "&b&lIsland Warps"
    headData: null
    headOwner: null
    lore:
    - "&7Need more island warps? Buy this"
    - "&7upgrade to increase your island warps."
    - ""
    - "&b&lInformation:"
    - "&b&l * &7Current Level: &b%level%"
    - "&b&l * &7Upgrade Cost: &b%crystalscost% Crystals and $%vaultcost%"
    - "&b&lLevels:"
    - "&b&l * &7Level 1: &b1 Warp"
    - "&b&l * &7Level 2: &b2 Warp"
    - "&b&l * &7Level 3: &b3 Warp"
    - "&b&l * &7Level 4: &b4 Warp"
    - "&b&l * &7Level 5: &b5 Warp"
    - ""
    - "&b&l[!] &bLeft Click to Purchase this Upgrade"
    slot: 14
  upgrades:
    1:
      money: 1000
      crystals: 15
      amount: 1
    2:
      money: 1000
      crystals: 15
      amount: 2
    3:
      money: 1000
      crystals: 15
      amount: 3
    4:
      money: 1000
      crystals: 15
      amount: 4
    5:
      money: 1000
      crystals: 15
      amount: 5
oresUpgrade:
  enabled: true
  item:
    material: "DIAMOND_ORE"
    amount: 1
    displayName: "&b&lIsland Generator"
    headData: null
    headOwner: null
    lore:
    - "&7Want to improve your generator? Buy this"
    - "&7upgrade to improve your island generator."
    - ""
    - "&b&lInformation:"
    - "&b&l * &7Current Level: &b%level%"
    - "&b&l * &7Upgrade Cost: &b%crystalscost% Crystals and $%vaultcost%"
    - ""
    - "&b&l[!] &bLeft Click to Purchase this Upgrade"
    slot: 15
  upgrades:
    1:
      money: 1000
      crystals: 15
      ores:
        COBBLESTONE: 3
        COAL_ORE: 1
      netherOres:
        BASALT: 1
    2:
      money: 1000
      crystals: 15
      ores:
        DIAMOND_ORE: 1
        IRON_ORE: 10
        REDSTONE_ORE: 10
        GOLD_ORE: 10
        LAPIS_ORE: 10
        COAL_ORE: 20
        COBBLESTONE: 40
      netherOres:
        BASALT: 20
        GLOWSTONE: 20
        NETHER_QUARTZ_ORE: 20
        NETHER_GOLD_ORE: 20
        NETHERRACK: 20
        ANCIENT_DEBRIS: 1
    3:
      money: 1000
      crystals: 15
      ores:
        DIAMOND_ORE: 10
        IRON_ORE: 10
        REDSTONE_ORE: 10
        GOLD_ORE: 10
        LAPIS_ORE: 10
        COAL_ORE: 20
        COBBLESTONE: 40
      netherOres:
        BASALT: 10
        GLOWSTONE: 10
        NETHER_QUARTZ_ORE: 10
        NETHER_GOLD_ORE: 10
        NETHERRACK: 10
        ANCIENT_DEBRIS: 1
`

**Comment by Farmeurimmo** [comment]
https://www.dropbox.com/s/1v6mx203olx76if/upgrades.yml?dl=1

**Comment by Farmeurimmo** [comment]
hum
I think I found something weird

**Comment by Farmeurimmo** [comment]
The plugin reset my upgrades.yml

**Comment by Farmeurimmo** [comment]
ANd now It's working, but WHY did the plugin is resetting my upgrades.yml sometimes on start?

**Comment by Faun471** [comment]
> And now It's working, but WHY did the plugin is resetting my upgrades.yml sometimes on start?
> There isn't any error.

The plugin will never reset your file if there are no errors. There is most likely an error that just went unnoticed.

**Comment by MertUnverdi** [comment]
Faun is smart and best so, he right
