### ISSUE TITLE
IridiumSkyblock, somehow break

### ISSUE THREAD

**Issue by ItzFabb-uwu** [Iridium-Development/IridiumSkyblock#352]
The bugs happend with /is create and when i edited the config it just got more worst

Server:
1.14.4 - Paper
Plugins:

![Screenshot_2021_0805_210327](https://user-images.githubusercontent.com/58950562/128364717-78cbbe11-9e81-4cce-9136-28c6b2635d15.png)

com.iridium.iridiumcore.dependencies.nbtapi.NbtApiException: Method not loaded! 'COMPOUND_SET_UUID'
        at com.iridium.iridiumcore.dependencies.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:160) ~[?:?]
        at com.iridium.iridiumcore.dependencies.nbtapi.NBTReflectionUtil.setData(NBTReflectionUtil.java:595) ~[?:?]
        at com.iridium.iridiumcore.dependencies.nbtapi.NBTCompound.setUUID(NBTCompound.java:485) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.setHeadData(ItemStackUtils.java:128) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:59) ~[?:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:75) ~[?:?]
        at com.iridium.iridiumskyblock.gui.SchematicGUI.addContent(SchematicGUI.java:32) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$null$3(IridiumSkyblock.java:194) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$4(IridiumSkyblock.java:191) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]

**Comment by dlsf** [comment]
Please use the template in the future. 

Further information from the Discord:
IridiumSkyblock 3.0.8

**Comment by ItzFabb-uwu** [comment]
![Screenshot_2021_0805_205023](https://user-images.githubusercontent.com/58950562/128393475-03adf469-acf6-4f5a-a300-bffd3f7eed52.png)


Idk if you able to see it, this is the error from 3.0.7, and when i update it to 3.0.8 still the same it also happends on 3.0.6 :/
