### ISSUE TITLE
epicspawners

### ISSUE THREAD

**Issue by dinobossytnew** [Iridium-Development/IridiumSkyblock#39]
[11:59:22 WARN]: [IridiumSkyblock] Task #289400 for IridiumSkyblock v2.6.7 generated an exception
java.lang.NoSuchMethodError: com.songoda.epicspawners.spawners.spawner.SpawnerManager.getSpawnerFromWorld(Lorg/bukkit/Location;)Lcom/songoda/epicspawners/spawners/spawner/Spawner;
at com.iridium.iridiumskyblock.support.EpicSpawners.getSpawnerAmount(EpicSpawners.java:13) ~[?:?]
at com.iridium.iridiumskyblock.Island.calculateIslandValue(Island.java:468) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by PeachesMLG** [comment]
https://github.com/Iridium-Development/IridiumSkyblock/issues/24
