### ISSUE TITLE
Plugin disabled [FIXED]

### ISSUE THREAD

**Issue by Mineswift** [Iridium-Development/IridiumSkyblock#396]
I just downloaded the plugin and it disabled on start,
im using minecraft version 1.16 and the iridium skyblock version 3.1.1
i only configured the sql.yml

sql.yml : 
---
driver: "MYSQL"
host: "localhost"
database: "root"
username: "root"
password: "root"
port: 3306
useSSL: false

Error.txt :

[16:46:38] [Server thread/ERROR]: Error occurred while enabling IridiumSkyblock v3.1.1 (Is it up to date?)
java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
	at java.nio.charset.CharsetDecoder.throwIllegalStateException(CharsetDecoder.java:989) ~[?:?]
	at java.nio.charset.CharsetDecoder.flush(CharsetDecoder.java:672) ~[?:?]
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:801) ~[?:?]
	at java.nio.charset.Charset.decode(Charset.java:814) ~[?:?]
	at org.sqlite.core.NativeDB.utf8ByteBufferToString(NativeDB.java:507) ~[server.jar:git-Purpur-"e581a73"]
	at org.sqlite.core.NativeDB.column_name(NativeDB.java:239) ~[server.jar:git-Purpur-"e581a73"]
	at org.sqlite.core.DB.column_names(DB.java:733) ~[server.jar:git-Purpur-"e581a73"]
	at org.sqlite.jdbc3.JDBC3Statement.getResultSet(JDBC3Statement.java:131) ~[server.jar:git-Purpur-"e581a73"]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:82) ~[server.jar:git-Purpur-"e581a73"]
	at com.iridium.iridiumskyblock.dependencies.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:66) ~[?:?]
	at com.iridium.iridiumskyblock.dependencies.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:56) ~[?:?]
	at com.iridium.iridiumskyblock.dependencies.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:254) ~[?:?]
	at com.iridium.iridiumskyblock.dependencies.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:203) ~[?:?]
	at com.iridium.iridiumskyblock.dependencies.ormlite.stmt.StatementExecutor.queryForAll(StatementExecutor.java:128) ~[?:?]
	at com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.queryForAll(BaseDaoImpl.java:252) ~[?:?]
	at com.iridium.iridiumskyblock.managers.tablemanagers.TableManager.<init>(TableManager.java:35) ~[?:?]
	at com.iridium.iridiumskyblock.managers.tablemanagers.IslandTableManager.<init>(IslandTableManager.java:17) ~[?:?]
	at com.iridium.iridiumskyblock.managers.DatabaseManager.init(DatabaseManager.java:70) ~[?:?]
	at com.iridium.iridiumskyblock.IridiumSkyblock.onEnable(IridiumSkyblock.java:137) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Purpur-"e581a73"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[server.jar:git-Purpur-"e581a73"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[server.jar:git-Purpur-"e581a73"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[server.jar:git-Purpur-"e581a73"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[server.jar:git-Purpur-"e581a73"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:454) ~[server.jar:git-Purpur-"e581a73"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:249) ~[server.jar:git-Purpur-"e581a73"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:929) ~[server.jar:git-Purpur-"e581a73"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:163) ~[server.jar:git-Purpur-"e581a73"]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[16:46:38] [Server thread/INFO]: [IridiumSkyblock] Disabling IridiumSkyblock v3.1.1
[16:46:38] [Server thread/ERROR]: Error occurred while disabling IridiumSkyblock v3.1.1 (Is it up to date?)
java.lang.NullPointerException: null
	at com.iridium.iridiumskyblock.IridiumSkyblock.saveData(IridiumSkyblock.java:300) ~[?:?]
	at com.iridium.iridiumcore.IridiumCore.onDisable(IridiumCore.java:72) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[server.jar:git-Purpur-"e581a73"]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[server.jar:git-Purpur-"e581a73"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[server.jar:git-Purpur-"e581a73"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[server.jar:git-Purpur-"e581a73"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[server.jar:git-Purpur-"e581a73"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[server.jar:git-Purpur-"e581a73"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[server.jar:git-Purpur-"e581a73"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:454) ~[server.jar:git-Purpur-"e581a73"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:249) ~[server.jar:git-Purpur-"e581a73"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:929) ~[server.jar:git-Purpur-"e581a73"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:163) ~[server.jar:git-Purpur-"e581a73"]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by MertUnverdi** [comment]
please use correct issue template
we need more clues
like ur sql.yml

**Comment by Mineswift** [comment]
> please use correct issue template
> we need more clues
> like ur sql.yml

done

**Comment by MertUnverdi** [comment]
U've censored or these is always root and localhost ???

**Comment by Mineswift** [comment]
> U've censored or these is always root and localhost ???

its always root and localhost

**Comment by MertUnverdi** [comment]
could you try set password empty `password: ""`

**Comment by MertUnverdi** [comment]
also did tried it on another plugins with this mysql info?

**Comment by Mineswift** [comment]
> also did tried it on another plugins with this mysql info?

yes i did this with luckperms too

**Comment by dlsf** [comment]
I'm pretty confused, the error message mentions SQLite instead of MySQL. Any ideas @PeachesMLG?

**Comment by MertUnverdi** [comment]
Fixed byself great
