### ISSUE TITLE
Disappearance of the islands

### ISSUE THREAD

**Issue by DoctaEnkoda** [Iridium-Development/IridiumSkyblock#489]
**Describe the bug**
On my 3 servers, I have over 3000 islands according to the Islands table but from time to time, I have players who no longer own their island for some unexplained reason. It's just the island_id value that disappears in users table, I manage to give them their island manually via a quick code. 

**To Reproduce**
Peut pas reproduire car c'est inexpliquable

**Server and Plugin Version**
Version : 
```
[15:45:59 INFO]: Checking version, please wait...
[15:46:00 INFO]: The_black_shade issued server command: /is go
[15:46:00 INFO]: This server is running Purpur version git-Purpur-1419 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: b72753c on ver/1.17.1)
[15:46:00 INFO]: You are 4 version(s) behind
Download the new version at: https://purpur.pl3x.net/downloads/
```
/is about
```
[15:46:41 INFO]: Plugin Name: IridiumSkyblock
[15:46:41 INFO]: Plugin Version: 3.1.5
[15:46:41 INFO]: Plugin Author: Peaches_MLG
[15:46:41 INFO]: Plugin Contributors: das_, SlashRemix
[15:46:41 INFO]: Plugin Donations: www.patreon.com/Peaches_MLG
```

**Comment by DoctaEnkoda** [comment]
I will try to explain at best because even I do not understand:

Occasionally, for no apparent reason, mostly island OWNERS lose their island_id / Role / Playtime.
The island still exists but it's really the user table that has a problem.

The users table is currently: 12266 rows.
From time to time, it comes back but it is quite rare.

I had to do this house code to give them back but it's clearly not clean:
```Java
try{
                Optional<User> user = IridiumSkyblock.getInstance().getUserManager().getUserByUUID(UUID.fromString(args[1]));
                User user1 = user.get();
                Island island = IridiumSkyblock.getInstance().getIslandManager().getIslandById(Integer.parseInt(args[0])).get();
                user1.setIsland(island);
                user1.setIslandRank(IslandRank.OWNER);
            } catch (Exception e) {
                sender.sendMessage(ChatColor.RED + e.getMessage());
            }
```

**Comment by PeachesMLG** [comment]
See if this is fixed in 3.2.0

**Comment by DoctaEnkoda** [comment]
Following this bug, during our tests, we saw that if a person who lost their island tries to recreate, the plugin crashes with its logs:
```
[20:37:13] [Thread-426/WARN]: java.sql.SQLException: Unable to run insert stmt on object com.iridium.iridiumskyblock.database.Island@5f5f4c0d: INSERT INTO `islands` (`name` ,`home` ,`visit` ,`create_time` ,`experience` ,`extra_value` ,`color` ) VALUES (?,?,?,?,?,?,?)
[20:37:13] [Thread-426/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.dependencies.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:25)
[20:37:13] [Thread-426/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:140)
[20:37:13] [Thread-426/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:465)
[20:37:13] [Thread-426/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:333)
[20:37:13] [Thread-426/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.dependencies.ormlite.dao.BaseDaoImpl.createOrUpdate(BaseDaoImpl.java:392)
[20:37:13] [Thread-426/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.managers.tablemanagers.TableManager.save(TableManager.java:59)
[20:37:13] [Thread-426/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.managers.DatabaseManager.lambda$registerIsland$3(DatabaseManager.java:137)
[20:37:13] [Thread-426/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
[20:37:13] [Thread-426/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[20:37:13] [Thread-426/WARN]: Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'Nuraka' for key 'sqlite_autoindex_islands_1'
[20:37:13] [Thread-426/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
[20:37:13] [Thread-426/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[20:37:13] [Thread-426/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[20:37:13] [Thread-426/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[20:37:13] [Thread-426/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[20:37:13] [Thread-426/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[20:37:13] [Thread-426/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
[20:37:13] [Thread-426/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.dependencies.ormlite.jdbc.JdbcDatabaseConnection.insert(JdbcDatabaseConnection.java:193)
[20:37:13] [Thread-426/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.dependencies.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:92)
[20:37:13] [Thread-426/WARN]: 	... 7 more
[20:37:13] [Thread-427/WARN]: java.util.concurrent.CompletionException: java.lang.ArithmeticException: / by zero
[20:37:13] [Thread-427/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[20:37:13] [Thread-427/WARN]: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[20:37:13] [Thread-427/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1766)
[20:37:13] [Thread-427/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[20:37:13] [Thread-427/WARN]: Caused by: java.lang.ArithmeticException: / by zero
[20:37:13] [Thread-427/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.database.Island.getCenter(Island.java:295)
[20:37:13] [Thread-427/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.database.Island.getPos1(Island.java:330)
[20:37:13] [Thread-427/WARN]: 	at IridiumSkyblock-3.2.2.jar//com.iridium.iridiumskyblock.managers.IslandManager.lambda$getIslandChunks$17(IslandManager.java:419)
[20:37:13] [Thread-427/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[20:37:13] [Thread-427/WARN]: 	... 1 more
```

**Comment by DoctaEnkoda** [comment]
I come to the news of this fact, players on our server always lose their island, even with the latest update
