### ISSUE TITLE
I use Mohist Interactive mod item error

### ISSUE THREAD

**Issue by yuankun1** [Iridium-Development/IridiumSkyblock#558]
I like this plugin very much
Which version is better

[20:23:30 ERROR]: Could not pass event PlayerInteractEvent to IridiumSkyblock v2.6.7
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:63) ~[EventExecutor.class:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:73) ~[TimedEventExecutor.class:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:331) ~[CraftEventFactory.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:501) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:1150) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:61) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(CPacketPlayerTryUseItemOnBlock.java:13) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_291]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:840) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_291]
Caused by: java.lang.IllegalArgumentException: Unsupported material with no data value: PIXELMON_PC
        at com.iridium.iridiumskyblock.xseries.XMaterial.lambda$matchXMaterial$0(XMaterial.java:1535) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_291]
        at com.iridium.iridiumskyblock.xseries.XMaterial.matchXMaterial(XMaterial.java:1535) ~[?:?]
        at com.iridium.iridiumskyblock.listeners.BlockPlaceListener.onBlockClick(BlockPlaceListener.java:122) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor830.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:?]
        ... 17 more

**Comment by dlsf** [comment]
1) We don't support IridiumSkyblock 2.6.7 anymore
2) We currently don't support modded servers with Spigot support like Mohist. I'm - thinking about adding support for 3.x, but you won't receive any new features for 2.x. 

For further questions about 3.x, please use our support Discord server.
