### ISSUE TITLE
AsyncPlayerChatEvent (Again)

### ISSUE THREAD

**Issue by Strahilchu** [Iridium-Development/IridiumSkyblock#587]
**Describe the bug**
This has appeared before and now seems to be back on my Skyblock server although I haven't touched anything. Everytime something is typed into chat by anyone it spams this log, any ideas?

[19:21:00 ERROR]: Could not pass event AsyncPlayerChatEvent to IridiumSkyblock v3.2.3
java.lang.NoClassDefFoundError: Could not initialize class com.iridium.iridiumskyblock.placeholders.Placeholders
        at com.iridium.iridiumskyblock.listeners.PlayerChatListener.onPlayerChat(PlayerChatListener.java:52) ~[IridiumSkyblock-3.2.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor365.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:git-Pufferfish-38]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[pufferfish-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:230) ~[pufferfish-1.18.1.jar:git-Pufferfish-38]
        at io.papermc.paper.adventure.ChatProcessor.processingLegacyFirst(ChatProcessor.java:115) ~[pufferfish-1.18.1.jar:git-Pufferfish-38]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:64) ~[pufferfish-1.18.1.jar:git-Pufferfish-38]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2205) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2116) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2082) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by MertUnverdi** [comment]
Weird

**Comment by dlsf** [comment]
Try restarting your server, don't reload. If that doesn't work, download the jar from SpigotMC again.

**Comment by Strahilchu** [comment]
I grabbed a newer jar from here and it's not showing anymore so I guess that did it, will close for now
