### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by afdsgihfjl** [Iridium-Development/IridiumSkyblock#658]
im trying to install the plugin but i get this error

[15:21:41 ERROR]: Could not load 'plugins\IridiumSkyblock-3.2.8 (1).jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Vault]. Please download and install these plugins to run 'IridiumSkyblock'.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-335]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-335]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-335]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-335]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

paper v1.18.2
java 18.0.1.1

**Comment by Faun471** [comment]
`Unknown/missing dependency plugins: [Vault]. Please download and install these plugins to run 'IridiumSkyblock'.` Please install Vault as stated [here.](https://docs.iridiumdevelopment.net/iridiumskyblock/#installation)

**Comment by MertUnverdi** [comment]
Ty Faun
