### ISSUE TITLE
1.19 still not working 

### ISSUE THREAD

**Issue by Kartingst** [Iridium-Development/IridiumSkyblock#676]
Plugin doesn't work on 1.19, I get this error every time 

[08:59:03] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to IridiumSkyblock v3.2.8
com.iridium.iridiumcore.dependencies.nbtapi.NbtApiException: [?]Error while calling the method 'getTagType(java.lang.String)', loaded: true, Enum: COMPOUND_GET_TYPE Passed Class: class java.lang.Boolean
	at com.iridium.iridiumcore.dependencies.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:180) ~[IridiumSkyblock-3.2.8 (1).jar:?]
	at com.iridium.iridiumcore.dependencies.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:631) ~[IridiumSkyblock-3.2.8 (1).jar:?]
	at com.iridium.iridiumcore.dependencies.nbtapi.NBTCompound.getType(NBTCompound.java:748) ~[IridiumSkyblock-3.2.8 (1).jar:?]
	at com.iridium.iridiumcore.dependencies.nbtapi.NBTCompound.addCompound(NBTCompound.java:556) ~[IridiumSkyblock-3.2.8 (1).jar:?]
	at com.iridium.iridiumcore.dependencies.nbtapi.NBTCompound.getOrCreateCompound(NBTCompound.java:594) ~[IridiumSkyblock-3.2.8 (1).jar:?]
	at com.iridium.iridiumskyblock.managers.IslandManager.getIslandCrystals(IslandManager.java:1065) ~[IridiumSkyblock-3.2.8 (1).jar:?]
	at com.iridium.iridiumskyblock.listeners.PlayerInteractListener.lambda$onPlayerInteract$0(PlayerInteractListener.java:45) ~[IridiumSkyblock-3.2.8 (1).jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at com.iridium.iridiumskyblock.listeners.PlayerInteractListener.onPlayerInteract(PlayerInteractListener.java:43) ~[IridiumSkyblock-3.2.8 (1).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor456.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-40]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.19.jar:git-Paper-40]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:527) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1872) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-40]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-40]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-40]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-40]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-40]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1462) ~[paper-1.19.jar:git-Paper-40]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-40]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-40]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@a27c024
	at jdk.internal.reflect.GeneratedMethodAccessor115.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at com.iridium.iridiumcore.dependencies.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:178) ~[IridiumSkyblock-3.2.8 (1).jar:?]
	... 32 more

**Comment by Strahilchu** [comment]
ETA on 1.19 ?

**Comment by MertUnverdi** [comment]
The plugin is recoding now, we didnt implemented 1.19 support yet but you can find a version is supports 1.19 On our discord server
