### ISSUE TITLE
Works on 1.19 but no menus work, here are the two errors that repeat

### ISSUE THREAD

**Issue by Strahilchu** [Iridium-Development/IridiumSkyblock#678]
[12:43:51 WARN]: [IridiumSkyblock] Task #186 for IridiumSkyblock v3.2.8 generated an exception
com.iridium.iridiumcore.dependencies.nbtapi.NbtApiException: [?]Error while calling the method 'getTagType(java.lang.String)', loaded: true, Enum: COMPOUND_GET_TYPE Passed Class: class java.lang.Boolean
        at com.iridium.iridiumcore.dependencies.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:180) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumcore.dependencies.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:631) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumcore.dependencies.nbtapi.NBTCompound.getType(NBTCompound.java:748) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumcore.dependencies.nbtapi.NBTCompound.addCompound(NBTCompound.java:556) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.setHeadData(ItemStackUtils.java:137) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:64) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumcore.utils.ItemStackUtils.makeItem(ItemStackUtils.java:85) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumskyblock.gui.ShopOverviewGUI.addContent(ShopOverviewGUI.java:47) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$3(IridiumSkyblock.java:209) ~[IridiumSkyblock-3.2.8.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock.lambda$onEnable$4(IridiumSkyblock.java:206) ~[IridiumSkyblock-3.2.8.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1517) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@46a6f202
        at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.iridium.iridiumcore.dependencies.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:178) ~[IridiumSkyblock-3.2.8.jar:?]
        ... 19 more
[12:44:15 ERROR]: Could not pass event PlayerInteractEvent to IridiumSkyblock v3.2.8
com.iridium.iridiumcore.dependencies.nbtapi.NbtApiException: [?]Error while calling the method 'getTagType(java.lang.String)', loaded: true, Enum: COMPOUND_GET_TYPE Passed Class: class java.lang.Boolean
        at com.iridium.iridiumcore.dependencies.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:180) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumcore.dependencies.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:631) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumcore.dependencies.nbtapi.NBTCompound.getType(NBTCompound.java:748) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumcore.dependencies.nbtapi.NBTCompound.addCompound(NBTCompound.java:556) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumcore.dependencies.nbtapi.NBTCompound.getOrCreateCompound(NBTCompound.java:594) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumskyblock.managers.IslandManager.getIslandCrystals(IslandManager.java:1065) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.iridium.iridiumskyblock.listeners.PlayerInteractListener.lambda$onPlayerInteract$0(PlayerInteractListener.java:45) ~[IridiumSkyblock-3.2.8.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at com.iridium.iridiumskyblock.listeners.PlayerInteractListener.onPlayerInteract(PlayerInteractListener.java:43) ~[IridiumSkyblock-3.2.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor514.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[petal-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[petal-api-1.19-R0.1-SNAPSHOT.jar:git-petal-"6202cf0"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[petal-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[petal-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:529) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1945) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1385) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1362) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[petal-1.19.jar:git-petal-"6202cf0"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@47ce92c4
        at jdk.internal.reflect.GeneratedMethodAccessor45.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.iridium.iridiumcore.dependencies.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:178) ~[IridiumSkyblock-3.2.8.jar:?]
        ... 32 more

PLUGINS: 
Plugins (30): AdvancedPortals, BottledExp, ChestCleaner, CMI, CMILib, CrazyAuctions, DeluxeMenus, dynmap, eco, EcoSkills, FeatherBoard, HeadDatabase, ImageMaps, IridiumSkyblock, LuckPerms, mcMMO, MobFarmManager, NBTAPI, PlaceholderAPI, ProMenus, ProtocolLib, RoseStacker, spark, TAB, Vault, VentureChat, Vulcan, WorldBorderAPI, WorldEdit, WorldGuard

**Comment by MertUnverdi** [comment]
The plugin is recoding now, we didnt implemented 1.19 support yet but you can find a version is supports 1.19 On our discord server
