### ISSUE TITLE
API getIslandViaLocation issue

### ISSUE THREAD

**Issue by OpenSource03** [Iridium-Development/IridiumSkyblock#723]
**Describe the bug**
I'm experiencing issues when using getIslandViaLocation. Error log and my code are below:

```
  public static String getLimit(Location location) {
    String islandId = null;

    try {
      if (Bukkit.getPluginManager().isPluginEnabled("BentoBox")) {
        islandId = getLimitBentoBox(location);
      } else if (Bukkit.getPluginManager().isPluginEnabled("SuperiorSkyblock2")) {
        islandId = getLimitSuperiorSkyblock(location);
      } else if (Bukkit.getPluginManager().isPluginEnabled("IridiumSkyblock")) {
        islandId = getLimitIridiumSkyblock(location);
      }
    } catch (NullPointerException ignored) {
      ignored.printStackTrace();
      return islandId;
    }

    return islandId;
  }

  public static String getLimitSuperiorSkyblock(Location location) {
    return SuperiorSkyblockAPI.getIslandAt(location)
        .getUniqueId()
        .toString();
  }

  public static String getLimitBentoBox(Location location) {
    return BentoBox.getInstance()
        .getIslands()
        .getIslandAt(location)
        .orElseThrow()
        .getUniqueId();
  }

  public static String getLimitIridiumSkyblock(Location location) {
    return String.valueOf(
        IridiumSkyblockAPI.getInstance()
            .getIslandViaLocation(location)
            .orElseThrow()
            .getId()
    );
  }
```

**To Reproduce**
1. Try getting island location by using getIslandViaLocation method.

**Expected behavior**

**Server and Plugin Version**
This server is running Paper version git-Paper-542 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: fa8fa1c)

[13:27:25 INFO]: Plugin Name: IridiumSkyblock
[13:27:25 INFO]: Plugin Version: 4.0.4
[13:27:25 INFO]: Plugin Author: Peaches_MLG
[13:27:25 INFO]: Plugin Donations: www.patreon.com/Peaches_MLG

**Logs**
```
[13:24:07 WARN]: java.lang.NullPointerException: Cannot invoke "com.iridium.iridiumskyblock.IridiumSkyblock.getIslandManager()" because "this.iridiumSkyblock" is null
[13:24:07 WARN]: 	at GensPlus.jar//com.iridium.iridiumskyblock.api.IridiumSkyblockAPI.getIslandViaLocation(IridiumSkyblockAPI.java:137)
[13:24:07 WARN]: 	at GensPlus.jar//xyz.arcadiadevs.gensplus.utils.SkyblockLimit.getLimitIridiumSkyblock(SkyblockLimit.java:47)
[13:24:07 WARN]: 	at GensPlus.jar//xyz.arcadiadevs.gensplus.utils.SkyblockLimit.getLimit(SkyblockLimit.java:20)
[13:24:07 WARN]: 	at GensPlus.jar//xyz.arcadiadevs.gensplus.models.LocationsData.createLocation(LocationsData.java:87)
[13:24:07 WARN]: 	at GensPlus.jar//xyz.arcadiadevs.gensplus.events.BlockPlace.onBlockPlace(BlockPlace.java:82)
[13:24:07 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor162.execute(Unknown Source)
[13:24:07 WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[13:24:07 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[13:24:07 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:24:07 WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:24:07 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[13:24:07 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[13:24:07 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:415)
[13:24:07 WARN]: 	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:408)
[13:24:07 WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:598)
[13:24:07 WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1959)
[13:24:07 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[13:24:07 WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[13:24:07 WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[13:24:07 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:24:07 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:24:07 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:24:07 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1342)
[13:24:07 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[13:24:07 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:24:07 WARN]: 	at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1319)
[13:24:07 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1312)
[13:24:07 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.br(IAsyncTaskHandler.java:114)
[13:24:07 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1428)
[13:24:07 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1174)
[13:24:07 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[13:24:07 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by OpenSource03** [comment]
The issue was that I did not set scope to provided.
