### ISSUE TITLE
PlayerTeleportEvent ERROR with AuthMe

### ISSUE THREAD

**Issue by SeussCZ** [Iridium-Development/IridiumSkyblock#732]
Hi, on the server we receive the Error message "Could not pass event PlayerTeleportEvent to IridiumSkyblock v4.0.4". I tried deleting the IridiumSkyblock folder, which didn't help. Subsequently. I tried to remove all the plugins on the server one by one, and I found out that this ERROR appears only when the AuthMe plugin (latest version) is on the server. If there is no AuthMe on the server, then ERROR does not appear, I would say that it is not a coincidence.

The previous version of IridiumSkyblock 4.0.3 did not have this error.

Paper version git-Paper-84 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: c016e03)

`[14:15:11] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to IridiumSkyblock v4.0.4
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getLocation()" because "player" is null
	at com.iridium.iridiumskyblock.database.User.getCurrentIsland(User.java:35) ~[IridiumSkyblock-4.0.4.jar:?]
	at com.iridium.iridiumskyblock.managers.IslandManager.getTeamViaPlayerLocation(IslandManager.java:88) ~[IridiumSkyblock-4.0.4.jar:?]
	at com.iridium.iridiumteams.listeners.PlayerTeleportListener.onPlayerTeleport(PlayerTeleportListener.java:28) ~[IridiumSkyblock-4.0.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor245.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-84]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1729) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1698) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1694) ~[?:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:313) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1587) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-84]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by PeachesMLG** [comment]
Should be fixed
