### ISSUE TITLE
 Cannot read field "money" because "schematicConfig.regenCost" is null

### ISSUE THREAD

**Issue by oldtian123** [Iridium-Development/IridiumSkyblock#771]
When I used the /is command to create an empty island, the server did not send me to the empty island. When I checked the server console, I saw the following error.
old_tian issued server command: /is
**_[23:17:01 WARN]: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot read field "money" because "schematicConfig.regenCost" is null
[23:17:01 WARN]:        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
[23:17:01 WARN]:        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
[23:17:01 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
[23:17:01 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[23:17:01 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[23:17:01 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
[23:17:01 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841)
[23:17:01 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
[23:17:01 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[23:17:01 WARN]: Caused by: java.lang.NullPointerException: Cannot read field "money" because "schematicConfig.regenCost" is null
[23:17:01 WARN]:        at IridiumSkyblock-4.0.8.jar//com.iridium.iridiumskyblock.managers.IslandManager.lambda$createTeam$6(IslandManager.java:185)
[23:17:01 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:17:01 WARN]:        ... 6 more_**
I have changed many economic plug-ins, including the Essentials plug-in you gave an example of, but it still cannot solve this problem.

**Comment by sh0inx** [comment]
see https://docs.iridiumdevelopment.net/en/Schematics
