### ISSUE TITLE
SHORT GRASS BlockBreakEvent Error

### ISSUE THREAD

**Issue by Kimryungyo1208** [Iridium-Development/IridiumSkyblock#786]
**Describe the bug**
Error every time SHORT_GRASS block is broken

**To Reproduce**

**Expected behavior**
I'm using the ItemsAdder Plugin. Could it be related to this?

**Server and Plugin Version**
> version
[14:13:17 INFO]: Checking version, please wait...
[14:13:18 INFO]: This server is running Paper version git-Paper-378 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: a58e29d)
You are 3 version(s) behind
Download the new version at: https://papermc.io/downloads/paper

> is about
[14:13:24 INFO]: Plugin Name: IridiumSkyblock
[14:13:24 INFO]: Plugin Version: 4.0.8
[14:13:24 INFO]: Plugin Author: Peaches_MLG
[14:13:24 INFO]: Plugin Donations: www.patreon.com/Peaches_MLG

**Screenshots**

**Logs**
If there are error messages in your console, please send them via [this](https://mclo.gs)
> error
[14:10:42 ERROR]: Could not pass event BlockBreakEvent to IridiumSkyblock v4.0.8
java.lang.IllegalArgumentException: Unsupported material with no data value: SHORT_GRASS
        at com.iridium.iridiumcore.dependencies.xseries.XMaterial.lambda$matchXMaterial$0(XMaterial.java:1817) ~[IridiumSkyblock-4.0.8.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.iridium.iridiumcore.dependencies.xseries.XMaterial.matchXMaterial(XMaterial.java:1817) ~[IridiumSkyblock-4.0.8.jar:?]
        at com.iridium.iridiumteams.listeners.BlockBreakListener.monitorBlockBreak(BlockBreakListener.java:51) ~[IridiumSkyblock-4.0.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor287.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-378]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-378]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-378]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:375) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:334) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:210) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1851) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-378]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-378]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-378]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-378]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-378]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-378]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-378]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-378]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Additional context**

**Comment by Henrizn** [comment]
I have this problem too, but only with BEDROCK players

**Comment by boiscljo** [comment]
SHORT_GRASS is a new block in 1.20.4(previously it was named GRASS), 4.0.8 isn't updated to know what it is. 4.0.9 should have 1.20.4 support. Beta releases are available on the discord for it.

**Comment by PeachesMLG** [comment]
Should be fixed
