### ISSUE TITLE
[1.16] Appache commons library missing

### ISSUE THREAD

**Issue by PeachesMLG** [Iridium-Development/IridiumSkyblock#862]
The apache commons library is missing in 1.16

```
[21:41:34] [Server thread/WARN]: [IridiumSkyblock] Task #4735 for IridiumSkyblock v4.0.9.1 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.iridium.iridiumskyblock.dependencies.iridiumcore.dependencies.iridiumcolorapi.IridiumColorAPI
    at com.iridium.iridiumskyblock.dependencies.iridiumcore.utils.StringUtils.color(StringUtils.java:25) ~[?:?]
    at com.iridium.iridiumskyblock.gui.SchematicGUI.getInventory(SchematicGUI.java:32) ~[?:?]
    at com.iridium.iridiumskyblock.managers.IslandManager.lambda$getSchematic$4(IslandManager.java:164) ~[?:?]
    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-794]
    at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-794]
    at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
    at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
    at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate [in thread "Server thread"]
    at com.iridium.iridiumskyblock.dependencies.iridiumcore.dependencies.iridiumcolorapi.IridiumColorAPI.getVersion(IridiumColorAPI.java:292) ~[?:?]
    at com.iridium.iridiumskyblock.dependencies.iridiumcore.dependencies.iridiumcolorapi.IridiumColorAPI.<clinit>(IridiumColorAPI.java:29) ~[?:?]
    at com.iridium.iridiumskyblock.dependencies.iridiumcore.utils.StringUtils.color(StringUtils.java:25) ~[?:?]
    at com.iridium.iridiumteams.listeners.PlayerJoinListener.lambda$onPlayerJoin$0(PlayerJoinListener.java:31) ~[?:?]
    ... 8 more
    ```

**Comment by sh0inx** [comment]
just did a test to replicate this, seems we either fixed it already or its working fine

**Comment by sh0inx** [comment]
will reopen if this continues to be a problem
