### ISSUE TITLE
TeamSpawner error

### ISSUE THREAD

**Issue by Bali0531-RC** [Iridium-Development/IridiumSkyblock#893]
### Steps to Reproduce

1. Place a spawner on the island.
2. Break the spawner.

### Expected Behavior

Break the spawner without erros.

### Actual Behavior

[17:23:30 ERROR]: Could not pass event BlockBreakEvent to IridiumSkyblock v4.1.0-B4
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.EntityType.name()" because the return value of "com.iridium.iridiumteams.database.TeamSpawners.getEntityType()" is null
        at com.iridium.iridiumskyblock.managers.DatabaseManager.lambda$init$7(DatabaseManager.java:82) ~[IridiumSkyblock-4.1.0-B4.jar:?]
        at com.iridium.iridiumskyblock.managers.tablemanagers.TableManager.getEntry(TableManager.java:78) ~[IridiumSkyblock-4.1.0-B4.jar:?]
        at com.iridium.iridiumskyblock.managers.IslandManager.getTeamSpawners(IslandManager.java:539) ~[IridiumSkyblock-4.1.0-B4.jar:?]
        at com.iridium.iridiumskyblock.managers.IslandManager.getTeamSpawners(IslandManager.java:50) ~[IridiumSkyblock-4.1.0-B4.jar:?]
        at com.iridium.iridiumteams.listeners.BlockBreakListener.lambda$monitorBlockBreak$1(BlockBreakListener.java:64) ~[IridiumSkyblock-4.1.0-B4.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at com.iridium.iridiumteams.listeners.BlockBreakListener.monitorBlockBreak(BlockBreakListener.java:58) ~[IridiumSkyblock-4.1.0-B4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor629.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:375) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:334) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:210) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1917) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1498) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1475) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1398) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:112) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1590) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Server Software & Minecraft Version

git-Purpur-2176

### IridiumSkyblock version

4.1.0-B4

### Server logs

https://mclo.gs/zEXYlYj

### Additional Comments

Also when I click on the spawner It sends this:
![image](https://github.com/user-attachments/assets/9a6a547e-4555-441c-b081-a848200b25ab)

**Comment by sh0inx** [comment]
we dont have any functionality for when you click on a spawner outside of updating the spawner in the database, so im not sure where or how this data is being printed to the chat

otherwise, is this an empty spawner? (a spawner that does not have a mob to spawn, or a null spawner)

**Comment by Bali0531-RC** [comment]
I just placed a normal spawner i don't know which one, we useing Aspawners as the spawner plugin. 
![image](https://github.com/user-attachments/assets/37469a21-cb4e-4650-b20b-12d378cd77d0) and that what we placed.

Also when there is a mob in the spawner there is no error.

**Comment by Bali0531-RC** [comment]
![image](https://github.com/user-attachments/assets/5a022dd1-7317-4bb1-b81f-033c893e88e4)

**Comment by sh0inx** [comment]
i imagine that checking for if the spawner is null like we do [here](https://github.com/Iridium-Development/IridiumTeams/blob/4485867fd877c8d3aedee7c66eccbe0babb1db39/src/main/java/com/iridium/iridiumteams/listeners/BlockPlaceListener.java#L59) but for the blockBreakEvent will correct this issue

**Comment by Bali0531-RC** [comment]
Okey

**Comment by sh0inx** [comment]
Fairly certain this was fixed in [Teams #48](https://github.com/Iridium-Development/IridiumTeams/pull/48)
